### ISSUE TITLE
[FEAT] 인증/인가 시스템 개선

### ISSUE THREAD

**Issue by selfishAltruism** [CAUCSE/CAUSW_frontend#65]
### 목적

> 로그인 이후 토큰 관리 및 라우터 관리 시스템 개선

### 작업 상세 내용

- [x] 로그인 유지 체크 박스 제거, 로그인 유지 기본 설정
- [x] 로그인 이후 사용자가 입력한 넣은 url로 이동
- [ ] 쿠키에 토큰 저장

**Comment by rbgksqkr** [comment]
개선은 refactor로 부탁드려요

**Comment by selfishAltruism** [comment]
기능 상으로 추가되는 부분이 있어서 일단 이번에는 feat로 유지하겠습니다.
다음부터는 refactor로 변경하겠습니다 :)

**Comment by rbgksqkr** [comment]
아하 그럼 메인이 되는걸 대괄호로 적고 Label 만 추가해주세요!
